--INSERT INTO destinations (name, country, description)
--VALUES
--    ('Amsterdam', 'Netherlands', 'Known for its picturesque canals and historic architecture.'),
--    ('Andorra la Vella', 'Andorra', 'A small capital nestled in the Pyrenees mountains.'),
--    ('Athens', 'Greece', 'The cradle of Western civilization with ancient ruins.'),
--    ('Belgrade', 'Serbia', 'Rich in history and cultural heritage.'),
--    ('Berlin', 'Germany', 'A vibrant, modern city with a storied past.'),
--    ('Bern', 'Switzerland', 'A picturesque capital in the heart of the Alps.'),
--    ('Bratislava', 'Slovakia', 'A charming city on the banks of the Danube River.'),
--    ('Brussels', 'Belgium', 'Home to the European Union and delectable chocolates.'),
--    ('Bucharest', 'Romania', 'A mix of old-world charm and modern development.'),
--    ('Budapest', 'Hungary', 'Famous for its thermal baths and stunning architecture.'),
--    ('Chisinau', 'Moldova', 'A lesser-known European capital with a rich history.'),
--    ('Copenhagen', 'Denmark', 'A city of bicycles, hygge, and royal palaces.'),
--    ('Dublin', 'Ireland', 'A city of literature, pubs, and friendly locals.'),
--    ('Helsinki', 'Finland', 'A design-forward city with beautiful waterfronts.'),
--    ('Lisbon', 'Portugal', 'A coastal capital with historic neighborhoods.'),
--    ('London', 'United Kingdom', 'A global metropolis with a rich cultural scene.'),
--    ('Luxembourg City', 'Luxembourg', 'A small city with a big role in the EU.'),
--    ('Madrid', 'Spain', 'The capital of Spain, known for its lively culture.'),
--    ('Minsk', 'Belarus', 'A city with a mix of Soviet history and modern development.'),
--    ('Monaco', 'Monaco', 'A glamorous city-state on the French Riviera.'),
--    ('Moscow', 'Russia', 'A city of rich history, architecture, and art.'),
--    ('Oslo', 'Norway', 'A capital surrounded by fjords and forests.'),
--    ('Paris', 'France', 'The City of Light, known for romance and art.'),
--    ('Podgorica', 'Montenegro', 'A Balkan capital with a growing tourism industry.'),
--    ('Prague', 'Czech Republic', 'A city of spires, beer, and a rich history.'),
--    ('Reykjavik', 'Iceland', 'A capital close to nature with geothermal springs.'),
--    ('Riga', 'Latvia', 'A Baltic capital with a stunning old town.'),
--    ('Rome', 'Italy', 'The Eternal City, filled with history and culture.');

--
--INSERT INTO activities (name, description, cost, destination_id)
--VALUES
--    ('Van Gogh Museum', 'Home to a vast collection of Van Gogh paintings and drawings.', 15.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Anne Frank House', 'Historic site where Anne Frank hid during WWII with her diary on display.', 14.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Rijksmuseum', 'National museum of the Netherlands with works by Rembrandt and Vermeer.', 20.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Keukenhof Gardens', 'Stunning flower gardens with vibrant tulip displays.', 18.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Amsterdam Canal Cruise', 'Explore the citys canals by boat for a unique perspective.', 25.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Vondelpark', 'A beautiful park for picnics, walks, and outdoor relaxation.', 0.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Heineken Experience', 'Learn about the famous Dutch beer brand with interactive exhibits.', 21.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Red Light District', 'Historic area with nightlife and entertainment.', 0.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Rembrandt House Museum', 'Explore the former home of the renowned painter Rembrandt.', 14.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('ADAM Lookout', 'Observation deck with panoramic views and a swing on the roof.', 13.50, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('NEMO Science Museum', 'Interactive science and technology museum for all ages.', 16.50, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Artis Royal Zoo', 'Visit a historic zoo with a variety of animals and gardens.', 23.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Amsterdam Museum', 'Explore the history and culture of the city of Amsterdam.', 15.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Jordaan Neighborhood', 'Charming area with canals, shops, and cafes.', 0.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Madame Tussauds Amsterdam', 'Wax museum featuring celebrity figures and interactive displays.', 24.50, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam'));
--    ('Hortus Botanicus Amsterdam', 'Botanical garden with a wide variety of plants and greenhouses.', 9.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('The Jordaan Food Tour', 'A guided culinary tour through the historic Jordaan neighborhood.', 45.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Molen van Sloten Windmill', 'A historic windmill with guided tours and great views.', 8.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Electric Ladyland', 'A unique museum of fluorescent art and minerals.', 10.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Amsterdam Dungeon', 'Interactive theatrical experience with a dark twist on history.', 21.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Houseboat Museum', 'Explore the interior of a traditional Dutch houseboat.', 5.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('NDSM Wharf', 'A creative and cultural hub with street art and industrial charm.', 0.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Tropenmuseum', 'Museum showcasing world cultures, art, and interactive exhibits.', 16.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('De Pijp Neighborhood', 'Vibrant area with markets, cafes, and the famous Albert Cuyp Market.', 0.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam')),
--    ('Amstelpark', 'A peaceful park with sculptures, gardens, and winding paths.', 0.00, (SELECT destination_id FROM travel_destination WHERE name = 'Amsterdam'));
--
--


----User that has all his itineraries as public (influencer)
--INSERT INTO itineraries (name, user_id, total_days, destination_id, is_public)
--VALUES
--('Paris Top Activities', 2, 3, 1, true),
--('Best Things to do in Santorini', 2, 4, 9, true);
----Add activities to the itineraries above
--INSERT INTO itinerary_activity (itinerary_id, activity_id)
--VALUES
--(1,1),
--(1,2),
--(1,3),
--(1,4),
--(2,71),
--(2,73),
--(2,75);